### ISSUE TITLE
手机访问文章页面出现位置错误

### ISSUE THREAD

**Issue by yanaex** [Yves-X/Copyright-for-Typecho#1]
![Image of Yaktocat](http://i1.buimg.com/1949/374757fcc22a73f6.jpg)

**Comment by Yves-X** [comment]
插件写入了版权信息，但没有对样式有任何设定，这种情况下具体显示效果由你的其他CSS决定。
如果你希望自定义样式，请自行引入CSS。版权信息已有类名`.content-copyright`，你无需对插件本身的代码做任何修改。
例如，你遇到的对齐问题可以通过这样一句CSS解决。
```css
.content-copyright p {
    text-align: left;
}
```
